#!/bin/bash
#PBS -P WCHPC
#PBS -N MPI
#PBS -l select=2:ncpus=24:mpiprocs=24
#PBS -l walltime=01:00:00
#PBS -q normal
#PBS -m abe
#PBS -M shaylin.vel@gmail.com
#PBS -r n
#PBS -o /mnt/lustre/users/student42/HPC_A1/std_out_mpi
#PBS -e /mnt/lustre/users/student42/HPC_A1/std_error_mpi
#PBS

module purge
module load chpc/parallel_studio_xe/18.0.2/2018.2.046
source /apps/compilers/intel/parallel_studio_xe_2018_update2/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpivars.sh
cd $PBS_O_WORKDIR
nproc=`cat $PBS_NODEFILE | wc -l`
exe=/home/student42/HPC_A1/mpi/bin/mpiSandpile
cp $PBS_NODEFILE hostfile
make run_mpi ARGS = "4 4 4 4"
